### ISSUE TITLE
return fuck

### ISSUE THREAD

**Issue by yushilong** [raof1313/FacViDownloader#1]
https://www.facebook.com/jocelyn.clark3/videos/2557241407620959/

https://m.facebook.com/story.php?story_fbid=2383998108384465&id=100003228965440

**Comment by raof1313** [comment]
You are missing something watch this video https://youtu.be/BWv5HulBO-E it has the explenation how to use the library also i have an app depending on this library and i have dowbloaded the video that you posted it link

**Comment by raof1313** [comment]
If it didn't work post your code and i will finde the issue

**Comment by raof1313** [comment]
probably you forgot the permissions

**Comment by yushilong** [comment]
But I am the result of running your demo.

**Comment by yushilong** [comment]
![image](https://user-images.githubusercontent.com/5087094/66629197-a52a2280-ec33-11e9-81a1-5c82c05aa2a1.png)

**Comment by raof1313** [comment]
If your internet connection is too slow it won't download because it renders a web page and extracts the download link from it and this exception means that it didn't render the page correctly so the download link wasn't complete

**Comment by raof1313** [comment]
![Screenshot_2019-10-11-16-57-25](https://user-images.githubusercontent.com/55064417/66658026-8311af80-ebf5-11e9-9eb4-c759f9abd6a1.png)

**Comment by raof1313** [comment]
![Screenshot_2019-10-11-16-58-43](https://user-images.githubusercontent.com/55064417/66658072-958be900-ebf5-11e9-8f4f-cfe3260b2eed.png)

**Comment by raof1313** [comment]
Bytheway the first video link does not exist so that's why you can't download it

**Comment by yushilong** [comment]
hello

**Comment by yushilong** [comment]
hello，Why is the url you load different from mine, how is your url generated?

**Comment by raof1313** [comment]
just copy the link from the facebook video from facebook app and then past it in the demo app that's all you need to do P.S: run the demo on a real device

**Comment by yushilong** [comment]
Can't I download it directly from my link?

**Comment by raof1313** [comment]
you need to get the link from facebook app, not from facebook webpage and if you don't mind please run the demo on a real device

**Comment by raof1313** [comment]
No, the library will not work on a webpage link sorry for that

**Comment by yushilong** [comment]
Ok, I got, thank you.
